-ifndef(epeg_parser_h).
-define(epeg_parser_h, 1).
-define(ANYCHAR, epeg_combinator:c_anychar).
-define(CHAR, epeg_combinator:c_char).
-define(CHARR, epeg_combinator:c_charrange).
-define(CHARC, epeg_combinator:c_charclass).
-define(STRING, epeg_combinator:c_string).
-define(THEN, epeg_combinator:c_then).
-define(SEQ, epeg_combinator:c_seq).
-define(PAND, epeg_combinator:c_pred_and).
-define(PNOT, epeg_combinator:c_pred_not).
-define(ORELSE, epeg_combinator:c_orelse).
-define(ALT, epeg_combinator:c_alt).
-define(REP, epeg_combinator:c_rep).
-define(MORE, epeg_combinator:c_more).
-define(OPT, epeg_combinator:c_option).
-define(SYM, epeg_combinator:c_symbol_get).
-define(SET(S, P), epeg_combinator:c_symbol_put(S, P)).
-define(STR(S), ??S).
-endif.
